name: 'Format'
on:
  - pull_request
  # - push
jobs:
  terraform:
    name: 'Format'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
        
      - name: Run a Terraform format    
        uses: docker://hashicorp/terraform:0.12.20
        with:
          entrypoint: terraform
          args: fmt -recursive
          
      - name: Commit changed files
        uses: stefanzweifel/git-auto-commit-action@v2.5.0
        with:
          commit_message: Apply formatting changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
